[project]
name = "test-files"
version = "0.1.0"
description = ""
authors = [{ name = "Frinze Erin Lapuz", email = "frinzekt@gmail.com" }]
requires-python = ">=3.12,<4"
readme = "README.md"
dependencies = ["django>=5.0.2,<6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
