name: "Devcontainer CI/CD"

on:
  push:
    branches: ["main", "NONE/setup-dev-containers"]
    paths:
      - cfc-devenv-base/**
      - .github/workflows/devcontainers.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: codersforcauses/cfc-devenv

jobs:
  # Build and push Docker image with Buildx (don't push on PR)
  # https://github.com/docker/build-push-action
  base-setup:
    # Permission for pushing to ghcr
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # To allow multiple platform
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # To allow pushing to registry
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-base

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ github.workspace}}/cfc-devenv-base/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-base:main
          cache-to: type=inline
          file: ${{ github.workspace}}/cfc-devenv-base/Dockerfile
          platforms: linux/amd64,linux/arm64

  arm64-setup:
    needs: base-setup
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Build and push Devcontainer image
        run: |
          npm install -g @devcontainers/cli
          export DOCKER_BUILDKIT=1
          devcontainer build --config cfc-devenv-base/devcontainer.json --workspace-folder . --push true --image-name ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --platform linux/arm64
  
  amd64-setup:
    needs: base-setup
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Build and push Devcontainer image
        run: |
          npm install -g @devcontainers/cli
          export DOCKER_BUILDKIT=1
          devcontainer build --config cfc-devenv-base/devcontainer.json --workspace-folder . --push true --image-name ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --platform linux/amd64
