name: "Devcontainer CI/CD"

on:
  push:
    branches: ["main", "NONE/setup-dev-containers"]
    paths:
      - .devcontainer/Dockerfile

jobs:
  # Build and push Docker image with Buildx (don't push on PR)
  # https://github.com/docker/build-push-action
  Build-Devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace}}/.devcontainer/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/codersforcauses/automatic-setups:main
          cache-to: type=inline
          file: ${{ github.workspace}}/.devcontainer/Dockerfile
          platforms: linux/amd64,linux/arm64
